stages:
  - test
  - build-image

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/backend/spring-server/.gradle"

cache:
  key: gradle-cache
  paths:
    - backend/spring-server/.gradle/wrapper
    - backend/spring-server/.gradle/caches

image: gradle:8.10.2-jdk17-alpine

unit-test:
  stage: test
  before_script:
    - cd backend/spring-server
    - gradle -v
  script:
    - ./gradlew --no-daemon clean test
  artifacts:
    when: always
    reports:
      junit: backend/spring-server/build/test-results/test/TEST-*.xml

.build_image_template:
  stage: build-image
  image: docker:27.3.1
  services:
    - name: docker:27.3.1-dind
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}" -f backend/spring-server/Dockerfile backend/spring-server
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH

build-image:
  extends: .build_image_template


